### ISSUE TITLE
conflict of my branch accouting-system

### ISSUE THREAD

**Issue by nesmamanasra** [nesmamanasra/boock-keeping-system#18]
![conflect](https://user-images.githubusercontent.com/52491098/177003447-b6d98bbb-e46e-4104-b2c3-22e12d6834bd.PNG)

![resolve-conflect](https://user-images.githubusercontent.com/52491098/177003460-fc038d9c-20ef-40bc-a07d-1018bf7266fc.PNG)

**Comment by nesmamanasra** [comment]
resolve conflict branch 'accounting system'

**Comment by BesanZeyad** [comment]
I watch nesma when she soleve this conflict, she's write some command on gitbash 
- git pull origin main
- code .
- solve conflict
- git status
- git commit
- git push origin 'branch' and comper pull request
